apiNames:
  - lisaapi1
backendNames:
  - none
diagnosticNames:
  - none
loggerNames:
  - none
namedValueNames:
  - lisaapi1namedvalue
productNames:
  - none
subscriptionNames:
  - none
versionSetNames:
  - none
groupNames:
  - none
PolicyFragmentNames:
  - none
tagNames:
  - none
