apiNames:
  - test
  - echo-api
backendNames:
  - none
diagnosticNames:
  - none
loggerNames:
  - none
productNames:
  - none
subscriptionNames:
  - none
tagNames:
  - none
versionSetNames:
  - none
groupNames:
  - none
PolicyFragmentNames:  [ ignore]
  
