apimServiceName: martinapimext
namedValues:
  - name: environment
    properties:
      displayName: environment
      value: "production"
apis:
  - name: test
    properites:
      displayName: "testapiinproduction111"
