apimServiceName: prod
namedValues:
  - name: environment
    properties:
      displayName: environment
      value: "production"
apis:
  - name: test
    properites:
      path: "/testprod"
      displayName: "testapiinproduction11"
