apiNames:
  - test-v2;rev=2
  - testapispec
  - test-v2
backendNames:
  - none
diagnosticNames:
  - none
loggerNames:
  - none
namedValueNames:
  - none
productNames:
  - none
subscriptionNames:
  - none
tagNames:
  - none
versionSetNames:
  - none
groupNames:
  - none
PolicyFragmentNames:
  - none
