apiNames:
  - test
  - test-v1
  - test-v2
backendNames:
  - none
diagnosticNames:
  - none
loggerNames:
  - none
productNames:
  - none
subscriptionNames:
  - none
tagNames:
  - none
versionSetNames:
  - 673787548eca5ee65e5867f9
groupNames:
  - none
PolicyFragmentNames:
  - none
  
