apiNames:
  - mattapi1
backendNames:
  - none
diagnosticNames:
  - none
loggerNames:
  - none
namedValueNames:
  - none
productNames:
  - none
subscriptionNames:
  - none
versionSetNames:
  - none
groupNames:
  - none
PolicyFragmentNames:
  - none
tagNames:
  - tag1
