apimServiceName: prod
namedValues:
  - name: environment
    properties:
      displayName: environment
      value: "production"
  - name: testSecret
    properties:
      displayName: testSecret
      value: "{#testSecretValue#}"         
apis:
 - name: test
   properties:
    path: testprod
    apiRevision: '1'
    authenticationSettings: {}
    description: 'hello there'
    displayName: hellothereinprod
    format:  openapi-link
    value: https://github.com/swagger-api/swagger-petstore/blob/master/src/main/resources/openapi.yaml
