apiNames:
  - martin-petstore
  - lisa-petstore
  - brian-petstore
backendNames:
  - none
diagnosticNames:
  - none
loggerNames:
  - none
namedValueNames:
  - none
productNames:
  - none
subscriptionNames:
  - none
tagNames:
  - none
versionSetNames:
  - none
groupNames:
  - none  
PolicyFragmentNames:
  - none
