apiNames:
  - api1
  - api2
backendNames:
  - none
diagnosticNames:
  - none
loggerNames:
  - none
namedValueNames:
  - none
productNames:
  - none
subscriptionNames:
  - none
tagNames:
  - none
versionSetNames:
  - none
PolicyFragmentNames:
  - none
