openapi: 3.0.1
info:
  title: te-msgraph
  description: ''
  version: ''
servers:
  - url: https://martinapimext.azure-api.net/temsgraph
paths:
  /me:
    get:
      summary: getprofile
      operationId: getprofile
      parameters:
        - name: Authorization
          in: header
          schema:
            type: ''
      responses:
        '200':
          description: 
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]