openapi: 3.0.1
info:
  title: httpbin
  description: ''
  version: ''
servers:
  - url: https://martinapimext.azure-api.net/httpbin
paths:
  /*:
    get:
      summary: WildcardGet
      operationId: wildcardget
      responses:
        '200':
          description: 
  /echo:
    post:
      summary: echo
      operationId: echo
      responses:
        '200':
          description: 
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]