on:
  workflow_dispatch:
    inputs:
      COMMITID:
        required: true
        type: string
      TAG:
        required: true
        type: string         
name: Create Release - V3

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: checkout-artifacts
        id: checkout-artifacts
        uses: actions/checkout@v4
        with:
         ref: 'artifacts'
         fetch-depth: 0
         fetch-tags: 'true'
         persist-credentials: 'true'
         token: ${{ secrets.ghpattoken }}         
      - name: create-release-tag
        id: create-release-tag
        uses: actions/create-release@v1
        env:
         GITHUB_TOKEN: ${{ secrets.ghpattoken }}
        with:
          commitish : ${{ inputs.COMMITID }}
          release_name: Release ${{ inputs.TAG }}
          tag_name: ${{ inputs.TAG }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false    
