openapi: 3.0.1
info:
  title: azurefunctionistiodemo
  description: Import from "azurefunctionistiodemo" Function App
  version: '1.0'
servers:
  - url: https://martinapimext.azure-api.net/azurefunctionistiodemo
paths:
  /HttpTriggerJava:
    post:
      summary: HttpTriggerJava
      operationId: post-httptriggerjava
      responses:
        '200':
          description: 
    get:
      summary: HttpTriggerJava
      operationId: get-httptriggerjava
      responses:
        '200':
          description: 
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]