openapi: 3.0.1
info:
  title: te
  description: ''
  version: '1.0'
servers:
  - url: https://martinapimext.azure-api.net/sftoken
paths:
  /gettoken:
    post:
      summary: requestsftoken
      operationId: requestsftoken
      requestBody:
        description: ''
        content:
          application/x-www-form-urlencoded:
            example: username=tifapprover@martin2176outlook.onmicrosoft.com&password=carT2176#&grant_type=password
      responses:
        '200':
          description: 
components:
  schemas:
    urlencodeddata:
      type: object
      properties:
        grant_type:
          type: string
        password:
          type: string
        username:
          type: string
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]