swagger: '2.0'
info:
  title: azurewebappistiodemo
  version: '1.0'
host: martinapimext.azure-api.net
basePath: /azurewebappistiodemo
schemes:
- https
securityDefinitions:
  apiKeyHeader:
    type: apiKey
    name: Ocp-Apim-Subscription-Key
    in: header
  apiKeyQuery:
    type: apiKey
    name: subscription-key
    in: query
security:
- apiKeyHeader: []
- apiKeyQuery: []
paths:
  /*:
    trace:
      operationId: 666b2231facff96e1d8b07a7
      summary: azurewebappistiodemo_TRACE
      responses:
        200:
          description: null
    head:
      operationId: 666b2231c67633061b98abee
      summary: azurewebappistiodemo_HEAD
      responses:
        200:
          description: null
    post:
      operationId: 666b22318ffbdc241b94a135
      summary: azurewebappistiodemo_POST
      responses:
        200:
          description: null
    get:
      operationId: 666b22312317fe1b3397683c
      summary: azurewebappistiodemo_GET
      responses:
        200:
          description: null
    delete:
      operationId: 666b223185cfec6b10a147ee
      summary: azurewebappistiodemo_DELETE
      responses:
        200:
          description: null
    options:
      operationId: 666b22313cafbe25d70e3169
      summary: azurewebappistiodemo_OPTIONS
      responses:
        200:
          description: null
    patch:
      operationId: 666b223130ef23575dbc59da
      summary: azurewebappistiodemo_PATCH
      responses:
        200:
          description: null
    put:
      operationId: 666b2231f702425a5f315050
      summary: azurewebappistiodemo_PUT
      responses:
        200:
          description: null
tags: []
