openapi: 3.0.1
info:
  title: httpbin
  description: ''
  version: version-b
servers:
  - url: https://martinapimext.azure-api.net/httpbin/version-b
paths:
  /headers:
    get:
      summary: callout
      description: callout
      operationId: callout
      responses:
        '200':
          description: 'null'
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]