name: Commit-Trigger-To-Publish-to-Dev
run-name: Commit-Trigger-To-Publish-to-Dev
#author martin francis kallukalam
#publish to dev apim instance from developer branch when a push/commit event happens on developer branch
on:
   push:
    paths: 
     - 'apimartifacts/**'
env:
  APIOPS_REPO: 'martin2176/apiops'
  PUBLISH_ARTIFACTS_CHOICE: "publish-artifacts-in-last-commit"
  BRANCH_TO_DEPLOY_FROM: ${{ github.ref_name }}
  REFTOCHECKOUTFOR_ARTIFACTS: "last commit"
  
jobs:
    Set-CommitID-to-Publish-Artifacts:
     name: Set-CommitID-to-Publish-Artifacts
     runs-on: ubuntu-latest
     steps:
      - name: printbranchname
        run: echo "${{ env.BRANCH_TO_DEPLOY_FROM }}"
      - name: set-commitid
        id: set-commitid
        run: |
         echo "COMMITID=${GITHUB_SHA}" >> "$GITHUB_OUTPUT"
         echo "PUBLISH_ARTIFACTS_CHOICE=publish-delta-artifacts-in-last-commit" >> "$GITHUB_OUTPUT"
         #echo "COMMITID_SHORT=$(git rev-parse --short ${GITHUB_SHA})" >> "$GITHUB_OUTPUT"
         #echo "COMMITID_SHORT=$(echo ${GITHUB_SHA} | cut -c1-7)" >> "$GITHUB_OUTPUT"
     outputs:
      COMMITID: ${{ steps.set-commitid.outputs.COMMITID }}
      PUBLISH_ARTIFACTS_CHOICE: ${{ steps.set-commitid.outputs.PUBLISH_ARTIFACTS_CHOICE }}
    
    Print-User-Selections:
     name: Print-User-Selections
     runs-on: ubuntu-latest
     needs: Set-CommitID-to-Publish-Artifacts
     steps:
      - name: print-user-selections
        id: print-user-selections
        run: |
         echo "ref to checkout artifacts(commitid): ${{ needs.Set-CommitID-to-Publish-Artifacts.outputs.COMMITID}}"
         echo "publish artifacts choice: ${{ needs.Set-CommitID-to-Publish-Artifacts.outputs.PUBLISH_ARTIFACTS_CHOICE}}"
         echo "branch to publish artifacts from: ${{ env.BRANCH_TO_DEPLOY_FROM }}"
    Deploy-to-Dev-APIM-Instance:
     #if: ${{ !always() }}
     name: Deploy-to-Dev-APIM-Instance
     needs: Set-CommitID-to-Publish-Artifacts
     uses: martin2176/apiops/.github/workflows/publish-into-environment.yaml@main
     with:
      COMMITID: ${{ needs.Set-CommitID-to-Publish-Artifacts.outputs.COMMITID }}
      PUBLISH_ARTIFACTS_CHOICE: ${{ needs.Set-CommitID-to-Publish-Artifacts.outputs.PUBLISH_ARTIFACTS_CHOICE }}
      API_MANAGEMENT_SERVICE_OUTPUT_FOLDER_PATH: apimartifacts
      CONFIGURATION_YAML_PATH: configuration-publisher-dev.yaml
      API_MANAGEMENT_ENVIRONMENT: dev
      BRANCH_TO_DEPLOY_FROM: ${{ env.BRANCH_TO_DEPLOY_FROM }}
     secrets: inherit
