on:
  workflow_dispatch:
    inputs:
      COMMITID:
        required: true
        type: string
      TAG:
        required: true
        type: string         
name: Create Release V1

jobs:
  build:
    name: Create Release v1
    runs-on: ubuntu-latest
    permissions:
     contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
         ref: 'artifacts'
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          commit : b3be9d7d79b8e1b268f13aa55fc4a22dfed3e51e
          name: Release ${{ inputs.TAG }}
          tag: ${{ inputs.TAG }}
          draft: false
          prerelease: false
          token: ${{ env.GITHUB_TOKEN }}
          replacesArtifacts: false
