on:
  workflow_dispatch:
    inputs:
      COMMITID:
        required: true
        type: string
      TAG:
        required: true
        type: string         
name: Create Release V1

jobs:
  build:
    name: Create Release v1
    runs-on: ubuntu-latest
    permissions:
     contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
         ref: 'artifacts'
      - name: Create Release
        run: |
         git tag -f {{ inputs.TAG }} {{ inputs.COMMITID }}
         git push origin {{ inputs.TAG }}
 
