on:
  workflow_dispatch:
    inputs:
      COMMITID:
        required: true
        type: string
      TAG:
        required: true
        type: string         
name: Create Release V2

jobs:
  build:
    name: Create Release v1
    runs-on: ubuntu-latest
    permissions:
     contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
         ref: 'artifacts'
      - name: Create Release
        run: |
         echo ${{ github.event.inputs.TAG }} ${{ github.event.inputs.COMMITID }}
         git tag ${{ github.event.inputs.TAG }} ${{ github.event.inputs.COMMITID }}
         git push origin ${{ inputs.TAG }}
 
