name: Manual-Trigger-To-Publish-to-Dev
run-name: Manual-Trigger-To-Publish-to-Dev
on:
   workflow_dispatch:
    inputs:
     PUBLISH_ARTIFACTS_CHOICE:
      description: 'Choose between the two options"'
      required: true
      type: choice
      default: "publish-artifacts-in-last-commit"
      options:
       - "publish-delta-artifacts-in-last-commit"
       - "publish-delta-artifacts-in-specific-commit"
     BRANCH_TO_DEPLOY_FROM:
      description: 'Enter the developer branch to deploy APIM artifacts from. Select your own developer branch'     
      required: true
      type: string
     REFTOCHECKOUTFOR_ARTIFACTS:
      description: 'Enter specific Commit ID in developer branch to look for artifacts.Default to the latest(last) commit'     
      required: true
      type: string
      default: "last commit"
env:
  APIOPS_REPO: 'martin2176/apiops'
  REFTOCHECKOUTFOR_ARTIFACTS: ${{ inputs.REFTOCHECKOUTFOR_ARTIFACTS == 'last commit' && 'inputs.BRANCH_TO_DEPLOY_FROM' || 'inputs.REFTOCHECKOUTFOR_ARTIFACTS' }}
  
  
jobs:
    Set-CommitID-to-Extract-Artifacts:
     if:  ${{ github.event_name == 'workflow_dispatch' }}
     name: Set-CommitID-to-Extract-Artifacts
     runs-on: ubuntu-latest
     steps:
      - name: checkout-developer-branch
        id: checkout-developer-branch
        uses: actions/checkout@v4
        with:
         ref: '${{ inputs.BRANCH_TO_DEPLOY_FROM }}'
         fetch-tags: 'false'
         fetch-depth: 15
      - name: set-commitid-on-manual-run-to-last-commit
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.REFTOCHECKOUTFOR_ARTIFACTS == 'last commit' }}
        id: set-commitid-on-manual-run-to-last-commit
        run: echo "COMMITID=$(git rev-parse HEAD)" >> $GITHUB_ENV
      - name: set-commitid-on-manual-run-to-specific-commit
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.REFTOCHECKOUTFOR_ARTIFACTS != 'last commit' }}
        id: set-commitid-on-manual-run-to-specific-commit
        run: echo "COMMITID=${{ inputs.REFTOCHECKOUTFOR_ARTIFACTS }}" >> $GITHUB_ENV
      - name: set-commitid
        id: set-commitid
        run: |
         echo "COMMITID=${COMMITID}" >> "$GITHUB_OUTPUT"
         echo "PUBLISH_ARTIFACTS_CHOICE=${{ inputs.PUBLISH_ARTIFACTS_CHOICE }}" >> "$GITHUB_OUTPUT"
     outputs:
      COMMITID: ${{ steps.set-commitid.outputs.COMMITID }}
      PUBLISH_ARTIFACTS_CHOICE: ${{ steps.set-commitid.outputs.PUBLISH_ARTIFACTS_CHOICE }}
    
    Print-User-Selections:
     name: Print-User-Selections
     runs-on: ubuntu-latest
     needs: Set-CommitID-to-Extract-Artifacts
     steps:
      - name: print-user-selections
        id: print-user-selections
        run: |
         echo "ref to checkout artifacts(commitid): ${{ needs.Set-CommitID-to-Extract-Artifacts.outputs.COMMITID}}"
         echo "publish artifacts choice: ${{ needs.Set-CommitID-to-Extract-Artifacts.outputs.PUBLISH_ARTIFACTS_CHOICE}}"

