name: PR-Merge-Trigger-On-Artifacts-Branch
run-name: PR-Merge-Trigger-On-Artifacts-Branch
on:
   pull_request:
    branches: [artifacts]
    types: [closed]
  
jobs:
    Set-CommitID-to-Extract-Artifacts:
     #if:  ${{ (github.event_name == 'pull_request' && github.event.pull_request.merged == true) }}
     if: startsWith(github.head_ref, 'working1')
     name: Set-CommitID-to-Extract-Artifacts
     runs-on: ubuntu-latest
     steps:
      - name: set-commitid
        id: set-commitid
        run: |
         echo "COMMITID=${GITHUB_SHA}" >> "$GITHUB_OUTPUT"
         echo "PUBLISH_ARTIFACTS_CHOICE=publish-delta-artifacts-in-last-commit" >> "$GITHUB_OUTPUT"
     outputs:
      COMMITID: ${{ steps.set-commitid.outputs.COMMITID }}
      PUBLISH_ARTIFACTS_CHOICE: ${{ steps.set-commitid.outputs.PUBLISH_ARTIFACTS_CHOICE }}
    
    Print-User-Selections:
     name: Print-User-Selections
     runs-on: ubuntu-latest
     needs: Set-CommitID-to-Extract-Artifacts
     steps:
      - name: print-user-selections
        id: print-user-selections
        run: |
         echo "commit id: ${{ needs.Set-CommitID-to-Extract-Artifacts.outputs.COMMITID}}"
         echo "publish artifacts choice: ${{ needs.Set-CommitID-to-Extract-Artifacts.outputs.PUBLISH_ARTIFACTS_CHOICE}}"
