#Reusable workflow
name: Publish-Artifacts-to-APIM-Environment-V1.0
run-name: Publish-Artifacts-to-APIM-Environment-V1.0
on:
  workflow_call:
    inputs:
      API_MANAGEMENT_ENVIRONMENT:
        required: true
        type: string
      CONFIGURATION_YAML_PATH:
        required: true
        type: string
      API_MANAGEMENT_SERVICE_OUTPUT_FOLDER_PATH:
        required: true
        type: string
      PUBLISH_ARTIFACTS_CHOICE:
        required: true
        type: string
      COMMITID:
        required: true
        type: string      
concurrency:
 group: publish-artifacts-to-apim-environment-${{ inputs.API_MANAGEMENT_ENVIRONMENT }}
 cancel-in-progress: false

env:
  apiops_release_version: v6.0.1.3
  Logging__LogLevel__Default: ${{ vars.LOG_LEVEL }}
  
jobs:
    Print-Input-From-Calling-Workflow:
     name: Print-Input-From-Calling-Workflow
     runs-on: ubuntu-latest
     environment: ${{ inputs.API_MANAGEMENT_ENVIRONMENT }}
     steps:
      - name: Print-Input-From-Calling-Workflow
        id: print-input-from-calling-workflow
        run: |
         echo "apimanagementenvironment is ${{ inputs.API_MANAGEMENT_ENVIRONMENT }}"
         echo "configurationyamlpath is ${{ inputs.CONFIGURATION_YAML_PATH }}"
         echo "apimanagementserviceoutputfolderpath is ${{ inputs.API_MANAGEMENT_SERVICE_OUTPUT_FOLDER_PATH }}"
         echo "publishartifacts is ${{ inputs.PUBLISH_ARTIFACTS_CHOICE }}"
         echo "commitid is ${{ inputs.COMMITID }}"
      - name: Checkout-Dev-Branch
        id: checkout-dev-branch
        if: ${{ inputs.API_MANAGEMENT_ENVIRONMENT == 'dev' }}
        uses: actions/checkout@v4
        with:
         ref: 'dev'
      - name: Copy-Dev-ConfigurationOverride-File
        id: copy-dev-configurationoverride-file
        if: ${{ inputs.API_MANAGEMENT_ENVIRONMENT == 'dev' }}
        run: |
         echo "Copying override configuration file to runner.temp"
         cp configuration-dev.yaml $RUNNER_TEMP/configuration-dev.yaml
         echo "Cat-ing override configuration file"
         cat $RUNNER_TEMP/configuration-dev.yaml
      - name: Checkout-Test-Branch
        id: checkout-test-branch
        if: ${{ inputs.API_MANAGEMENT_ENVIRONMENT == 'test' }}
        uses: actions/checkout@v4
        with:
         ref: 'test'
      - name: Copy-Test-ConfigurationOverride-File
        id: copy-test-configurationoverride-file
        if: ${{ inputs.API_MANAGEMENT_ENVIRONMENT == 'test' }}
        run: |
         echo "Copying override configuration file to runner.temp"
         cp configuration-test.yaml $RUNNER_TEMP/configuration-test.yaml
         echo "Cat-ing override configuration file"
         cat $RUNNER_TEMP/configuration-test.yaml
      - name: Checkout-Prod-Branch
        id: checkout-prod-branch
        if: ${{ inputs.API_MANAGEMENT_ENVIRONMENT == 'prod' }}
        uses: actions/checkout@v4
        with:
         ref: 'prod'
      - name: Copy-Prod-ConfigurationOverride-File
        id: copy-prod-configurationoverride-file
        if: ${{ inputs.API_MANAGEMENT_ENVIRONMENT == 'prod' }}
        run: |
         echo "Copying override configuration file to runner.temp"
         cp configuration-prod.yaml $RUNNER_TEMP/configuration-prod.yaml
         echo "Cat-ing override configuration file"
         cat $RUNNER_TEMP/configuration-prod.yaml