name: Extract-From-Dev-APIM-Instance

on:
  workflow_dispatch:
    inputs:
      REFTOCHECKOUTFOR_CONFIGURATIONYAMLPATH:
        description: 'Choose the REF to use to checkout the extractor config file (Enter specific commit from Dev branch or defaults to latest commit from dev branch)'     
        required: true
        type: string
        default: dev
      CONFIGURATION_YAML_PATH:
        description: 'Choose whether to extract all APIM artifacts OR extract only APIM artifacts listed in extractor config file'     
        required: true
        type: choice
        options:
        - 'Extract Selected APIM Artifacts'
        - 'Extract All APIM Artifacts'
      API_SPECIFICATION_FORMAT:
        description: 'API specification format to extract the API spec'     
        required: true
        type: choice
        options:
        - OpenAPIV3Yaml 
        - OpenAPIV3Json
        - OpenAPIV2Yaml
        - OpenAPIV2Json
        default: OpenAPIV3Yaml
      REFERENCE_NUMBER:
        description: 'Reference(ticket) number to include in the title of PR'     
        required: true
        type: string
        default: '0000000'

concurrency:
 group: extract-from-dev-apim-instance
 cancel-in-progress: false    

env:
  apiops_release_version: v6.0.1.3

jobs:
  Extract-Artifacts:
    runs-on: ubuntu-latest
    environment: dev 
    steps:
      - name: Checkout-Configuration-File
        uses: actions/checkout@v4
        with:
         ref: '${{ github.event.inputs.REFTOCHECKOUTFOR_CONFIGURATIONYAMLPATH }}'
        
      - name: Run-Extractor
        env:
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          AZURE_RESOURCE_GROUP_NAME: ${{ secrets.AZURE_RESOURCE_GROUP_NAME }}
          API_MANAGEMENT_SERVICE_NAME: ${{ secrets.API_MANAGEMENT_SERVICE_NAME }}
          API_MANAGEMENT_SERVICE_OUTPUT_FOLDER_PATH: ${{ GITHUB.WORKSPACE }}/apimartifacts  # change this to the artifacts folder
          API_SPECIFICATION_FORMAT: ${{ github.event.inputs.API_SPECIFICATION_FORMAT }}
          #Logging__LogLevel__Default: Trace
          CONFIGURATION_YAML_PATH:  ${{ GITHUB.WORKSPACE }}/configuration.extractor.yaml
        run: |
          #$var1="${{ github.event.inputs.CONFIGURATION_YAML_PATH }}"
          #$var2="Extract All APIM Artifacts"
          #$var3="Extract Selected APIM Artifacts"
          #if ($var1 -eq $var3) 
          #{
          #Write-Output "User have chosen to extract Selected APIM Artifacts"
          #echo "Copying extractor configuration file to runner.temp"
          #copy configuration.extractor.yaml $env:RUNNER_TEMP
          #$env:CONFIGURATION_YAML_PATH="$env:RUNNER_TEMP/configuration.extractor.yaml"
          #$env:CONFIGURATION_YAML_PATH
          #$env:API_SPECIFICATION_FORMAT
          cat $env:CONFIGURATION_YAML_PATH
          #}
          #else
          #{
          #Write-Output "User have chosen to extract All APIM Artifacts"
          #}
          Set-StrictMode -Version Latest
          $ErrorActionPreference = "Stop"
          $VerbosePreference = "Continue"
          $InformationPreference = "Continue"

          Write-Information "Setting name variables..."
          $releaseFileName = "extractor-linux-x64.zip"
          $executableFileName = "extractor"

          if ("${{ runner.os }}" -like "*win*") {
            $releaseFileName = "extractor-win-x64.zip"
            $executableFileName = "extractor.exe"
          }
          elseif ("${{ runner.os }}" -like "*mac*" -and "${{ runner.arch }}" -like "*arm*") {
            $releaseFileName = "extractor-osx-arm64.zip"
          }
          elseif ("${{ runner.os }}" -like "*mac*" -and "${{ runner.arch }}" -like "*x86_64*") {
            $releaseFileName = "extractor-osx-x64.zip"
          }

          Write-Information "Downloading release..."
          $uri = "https://github.com/Azure/apiops/releases/download/${{ env.apiops_release_version }}/$releaseFileName"
          $downloadFilePath = Join-Path "${{ runner.temp }}" $releaseFileName
          Invoke-WebRequest -Uri "$uri" -OutFile "$downloadFilePath"

          Write-Information "Extracting release..."
          $executableFolderPath = Join-Path "${{ runner.temp }}" "extractor"
          Expand-Archive -Path "$downloadFilePath" -DestinationPath "$executableFolderPath"
          $executableFilePath = Join-Path "$executableFolderPath" $executableFileName

          Write-Information "Setting file permissions..."
          if ("${{ runner.os }}" -like "*linux*")
          {
            & chmod +x "$executableFilePath"
            if ($LASTEXITCODE -ne 0) { throw "Setting file permissions failed."}
          }

          Write-Information "Running extractor..."
          & "$executableFilePath"              
          if ($LASTEXITCODE -ne 0) { throw "Running extractor failed."}

          Write-Information "Execution complete."
          ls -R $env:API_MANAGEMENT_SERVICE_OUTPUT_FOLDER_PATH
        shell: pwsh
      
      - name: Upload-Artifact
        uses: actions/upload-artifact@v4
        env:
          API_MANAGEMENT_SERVICE_OUTPUT_FOLDER_PATH: ${{ GITHUB.WORKSPACE }}/apimartifacts
          #API_MANAGEMENT_SERVICE_OUTPUT_FOLDER_PATH: apimartifacts  # change this to the artifacts folder  
        with:
          name: artifact-extract-from-dev-apim-instance
          #path: ${{ env.API_MANAGEMENT_SERVICE_OUTPUT_FOLDER_PATH }}/${{ env.API_MANAGEMENT_SERVICE_OUTPUT_FOLDER_PATH }}
          path: ${{ env.API_MANAGEMENT_SERVICE_OUTPUT_FOLDER_PATH }}
          overwrite: 'true'

