name: Run - Publisher Original

on:
  # Triggers the workflow on pull request events but only for the main branch
  #pull_request:
   # branches: [main]
    #types: [closed]
  workflow_dispatch:    
   inputs:
     COMMIT_ID_CHOICE:
      description: |
       'Choose "publish-all-artifacts-in-repo" only when you want to force republishing all artifacts (e.g. after build failure)' 
        'Otherwise stick with either "publish-delta-artifacts-in-specific-commit" or "publish-artifacts-in-last-commit"'
      required: true
      type: choice
      default: "publish-delta-artifacts-in-specific-commit"
      options:
         - "publish-delta-artifacts-in-last-commit"
         - "publish-all-artifacts-in-repo"
         - "publish-delta-artifacts-in-specific-commit"

     REFTOCHECKOUTFOR_ARTIFACTS:
       description: 'Enter specific Commit ID in Artifacts branch to look for artifacts.Defaults is the latest commit from Artifacts branch'     
       required: true
       type: string
       default: "artifacts"

     API_MANAGEMENT_ENVIRONMENT:
       description: 'Choose the environment'     
       required: true
       type: environment
       default: "dev"

jobs:
  get-commit:
    runs-on: ubuntu-latest
    steps:
      # Set the COMMIT_ID env variable
      - name: Set the Commit Id
        id: commit
        run: echo "commit_id=${GITHUB_SHA}" >> "$GITHUB_OUTPUT"
      - name: printcommitid
        id: printcommitid
        run: echo "commit_id=${GITHUB_SHA}"       
    outputs:
      commit_id: ${{ steps.commit.outputs.commit_id }}
